import = ["./catppuccin-mocha.toml"]
live_config_reload = true

[window]
decorations = "None"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[scrolling]
history = 5000
multiplier = 10

[font]
size = 11.5
offset = { x = 0, y = 2 }

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On"}
unfocused_hollow = true
thickness = 0.3

[mouse]
hide_when_typing = true

